#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database
- name: Run PostgreSQL container
  community.docker.docker_container:
    name: database
    image: aymenn8/tp-devops-database:latest
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: "{{ database_user }}"
      POSTGRES_PASSWORD: "{{ database_password }}"
      POSTGRES_DB: "{{ database_name }}"

    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - name: network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
