#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app
- name: Run App container
  community.docker.docker_container:
    name: simple-api
    image: aymenn8/tp-devops-simple-api:latest
    state: started
    restart_policy: always
    published_ports:
      - "8080:8080"
    networks:
      - name: network
    env:
      DATABASE_HOST: "{{ database_host }}"
      DATABASE_PORT: "{{ database_port }}"
      DATABASE_NAME: "{{ database_name }}"
      DATABASE_USER: "{{ database_user }}"
      DATABASE_PASSWORD: "{{ database_password }}"

  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
