- hosts: all
  become: true

  vars:
    database_host: database
    database_port: "5432"
    database_name: db
    database_user: usr
    database_password: pwd

  roles:
    - docker
    - network
    - database
    - app
    - proxy
