# To run this playbook, use the following command:
# ansible-playbook -i inventory.ini playbook.yml --vault-password-file vault_password.txt

- hosts: all
  become: true

  vars_files:
    - vars/secrets.yml

  roles:
    - docker
    - network
    - database
    - app
    - proxy
