- hosts: all
  become: true

  vars:
    database_host: ${{secrets.DATABASE_HOST}}
    database_port: ${{secrets.DATABASE_PORT}}
    database_name: ${{secrets.DATABASE_NAME}}
    database_user: ${{secrets.DATABASE_USER}}
    database_password: ${{secrets.DATABASE_PASSWORD}}

  roles:
    - docker
    - network
    - database
    - app
    - proxy
