#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/proxy
- name: Run HTTPD proxy container
  community.docker.docker_container:
    name: my_proxy
    image: aymenn8/tp-devops-httpd:latest
    state: started
    restart_policy: always
    published_ports:
      - "80:80"
    networks:
      - name: network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
